version: '3.8'


services:
  app:
    build: .
    volumes:
      - ./src/:/opt/app
    ports:
      - "8080:8080"
    env_file:
      - environment/local.env
    depends_on:
      - db
    environment:
      DB_HOST: db
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - environment/local.env
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: