name: Linters

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    strategy:
      matrix:
        linter: [flake8, mypy]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.13

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry=="1.6.1"

      - name: Install dependencies
        run: poetry install

      - name: Run ${{ matrix.linter }}
        run: poetry run ${{ matrix.linter }} .